### ISSUE TITLE
Custodes hetaeron guard unit size displaying incorrectly when vexilla and sentinel blade selected

### ISSUE THREAD

**Issue by Sera-A-H** [BSData/horus-heresy#3165]
**Describe the bug**
Custodes hetaeron guard unit size displaying incorrectly when vexilla and sentinel blade selected - choosing vexilla and SB adds an additional +1 to unit size, but the points remain correct (Bug appearing specifically on NewRecruit)

**To Reproduce**
1. in a legio custodes detachment, add a unit of hetaeron guard
2. add an additional guard up to 4, which currently reads correctly
3. change weapon selection from meridian swords to "vexilla and sentinel blade"
4.  points cost increases by expected 20pts, but squad sizes erroneously increases by 1 (up to 5)

**Device and data (please complete the following information):**
 - iOS, Safari
 - Site: New Recruit

**Comment by Mayegelt** [comment]
This seemed to have been resolved at some point.

**Comment by The4D6** [comment]
Is this issue fixed but not released? It still appears to be present on new recruit

**Comment by Mayegelt** [comment]
Misunderstood the display issue. Got a fix now put up in #3302
It seems that the 5 weapon options were also being classified as "Model" rather than upgrade.
