### ISSUE TITLE
[Astarte Equipment] Misc Weapons missing profiles

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#582]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.00.13

**Platform:** Android

**Dropbox:** No

**Description:** I'm currently building a horus heresy list and I'm not getting some of the statlines for certain weapons like: lightning claws, heavy flamers, power swords, multi-meltas, twin-linked bolters, or hunter-killer missiles. I am also not getting the upgraded armor save from artificer armor

**Comment by zopha** [comment]
Add/update statlines for the following weapons:

- [ ] lightning claws
- [ ] heavy flamers
- [ ] power swords
- [ ] multi-meltas
- [ ] twin-linked bolters
- [ ] hunter-killer missiles
- [ ] Investigate/Update Artificer Armour save


Should have hunter-killer missiles sorted soon, just have to get an updated Vehicle wargear options branch finished and I'll submit it for review/QA. I'd like to finish the Heavy Support slot options before moving on so I should be able to build the shared groundwork for the in that branch if anyone else wants to work on the melee weapons.

**Comment by ghoulcaller** [comment]
I have found that regular flamers dont have statlines either

**Comment by capitaladot** [comment]
@zopha did these get done?

**Comment by zopha** [comment]
I've been looking back at this one and realised it's too vague due to the amount of squads and units that need to be updated.

All the other Profiles and rules have been added to the GST and CAL files.

The only thing I didn't start on was the Artificer armour stat line change. I started with the Praetor but that has to be redone.

**Comment by ghoulcaller** [comment]
The only profiles I see missing now are the preators power weapons and the
terminators power weapons, power fist, chainfist and combi-bolters. The
rest are fixed thank you.

**Comment by zopha** [comment]
I have one group of weapons sorted for the praetor, I just need to replicate it to the other groups for that unit. The list is basically the same for the centurion but with added consul restrictions.

Elites and HQ units are the sets I didn't get around to work on when I was doing my standard units review.

**Comment by alphalas** [comment]
Combat shields in the LCS are still missing - it's something that probably should be left open until we're done the rewrite
